version: "3.9"

services:

  nginx:
    image: mohsinredian/wordpress-nginx:latest
    container_name: wordpress-nginx
    restart: unless-stopped

    ports:
      - "${NGINX_PORT}:80"

    volumes:
      - ./:/var/www/html

    depends_on:
      - php

    networks:
      - wordpress


  php:
    image: mohsinredian/wordpress-php:latest
    container_name: wordpress-php
    restart: unless-stopped

    volumes:
      - ./:/var/www/html

    depends_on:
      - mysql

    networks:
      - wordpress


  mysql:
    image: mysql:8.0
    container_name: wordpress-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/wordpress.sql:/docker-entrypoint-initdb.d/wordpress.sql

    networks:
      - wordpress


volumes:
  mysql_data:


networks:
  wordpress:
